### ISSUE TITLE
[Feature] Dex prices page.

### ISSUE THREAD

**Issue by 27aume** [pbca26/komodo-omni-explorer#9]
would be nice if in extra to the search bar we could have a small box with scroll down menu to pick base currency we want to see prices. Filter work but shows a currency pair in both sides KMD/REVS - REVS/KMD
Using the base currency box could show only pairs on a defined base.

Thank you 👍

**Comment by pbca26** [comment]
you can use full pair name for now
e.g. if you want to see kmd/revs type kmd/revs in the filter field
